# Generated by Django 4.2.3 on 2023-09-27 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_usersubpaymenthistory_has_partial_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubcription",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
