# Generated by Django 4.2.5 on 2024-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_userwalletaddress_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubcription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
