# Generated by Django 4.2.3 on 2023-09-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("binarytree", "0002_mlmbinary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmbinary",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="binarytree.mlmbinary",
            ),
        ),
    ]
