# Generated by Django 4.2.3 on 2023-09-29 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("binarytree", "0003_alter_mlmbinary_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmbinary",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mlmbinary",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_user",
                to="binarytree.mlmbinary",
            ),
        ),
        migrations.AlterField(
            model_name="mlmbinary",
            name="user_left",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="left",
                to="binarytree.mlmbinary",
            ),
        ),
        migrations.AlterField(
            model_name="mlmbinary",
            name="user_right",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="right",
                to="binarytree.mlmbinary",
            ),
        ),
    ]
