# Generated by Django 4.2.3 on 2023-10-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("binarytree", "0005_forcedmatrix"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ForcedMatrix",
        ),
    ]
