# Generated by Django 4.2.5 on 2023-10-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("binarytree", "0006_delete_forcedmatrix"),
        (
            "binarytree",
            "0006_remove_mlmrank_referrals_remove_mlmrank_team_size_and_more",
        ),
    ]

    operations = []
