# Generated by Django 4.2.5 on 2023-11-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binarytree', '0011_alter_binaryparents_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmrank',
            name='rank_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/ranks/%Y/%m/%d/'),
        ),
    ]
