# Generated by Django 4.2.5 on 2024-04-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binarytree", "0012_mlmrank_rank_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmrank",
            name="equivalent_name",
            field=models.CharField(
                choices=[
                    ("Pawn", "Pawn"),
                    ("Knight", "Knight"),
                    ("Bishop", "Bishop"),
                    ("Rook", "Rook"),
                    ("Queen", "Queen"),
                    ("King", "King"),
                ],
                default="Pawn",
                max_length=25,
            ),
        ),
    ]
