# Generated by Django 4.2.5 on 2024-04-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binarytree", "0014_remove_mlmrank_max_referrals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmrank",
            name="separate_enroller_tree_conditions",
            field=models.JSONField(default=dict),
        ),
    ]
