# Generated by Django 4.2.5 on 2024-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binarytree", "0015_alter_mlmrank_separate_enroller_tree_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmrank",
            name="rank_level",
            field=models.IntegerField(default=0),
        ),
    ]
