# Generated by Django 4.2.5 on 2024-04-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binarytree", "0016_mlmrank_rank_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmrank",
            name="separate_enroller_tree_conditions",
            field=models.JSONField(null=True),
        ),
    ]
