# Generated by Django 4.2.3 on 2023-09-18 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("signalbot", "0003_remove_tradesignals_trade_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradesignals",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
