# Generated by Django 4.2.3 on 2023-10-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signalbot', '0005_signalfollowedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tradesignals',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalbot.tradesymbol'),
        ),
    ]
