# Generated by Django 4.2.3 on 2023-10-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalbot', '0006_tradesymbol_alter_tradesignals_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesymbol',
            name='base_asset',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradesymbol',
            name='quote_asset',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
