# Generated by Django 4.2.3 on 2023-10-11 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signalbot', '0010_portfolio_stop_price_portfolio_take_profit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalWithdrawlHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('txid', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('fee_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('money_allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_allocated_to', to=settings.AUTH_USER_MODEL)),
                ('refered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refered_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Binawallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinaryWithDrawlHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('txid', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('fee_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinaryIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('for_month', models.DateField()),
                ('money_allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_money_allocated_to', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
