# Generated by Django 4.2.5 on 2023-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "signalbot",
            "0011_referalwithdrawlhistory_referalwallet_referalincome_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradehistory",
            name="trade_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
