# Generated by Django 4.2.5 on 2023-10-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signalbot", "0012_alter_tradehistory_trade_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referalincome",
            name="is_withdrawn",
        ),
    ]
