# Generated by Django 4.2.5 on 2023-10-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signalbot", "0012_takeprofits_tradesignals_trade_type_and_more"),
        ("signalbot", "0014_alter_referalwallet_user"),
    ]

    operations = []
