# Generated by Django 4.2.5 on 2024-04-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalbot", "0016_remove_tradesignals_take_profit_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradesignals",
            name="amount_2",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tradesignals",
            name="amount_3",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tradesignals",
            name="amount_4",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tradesignals",
            name="percentage_2",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tradesignals",
            name="percentage_3",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tradesignals",
            name="percentage_4",
            field=models.FloatField(default=0),
        ),
    ]
