# Generated by Django 4.2.5 on 2024-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalbot", "0017_alter_tradesignals_amount_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradehistory",
            name="timestamp",
            field=models.BigIntegerField(default=0),
        ),
    ]
