# Generated by Django 4.2.3 on 2023-09-11 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
