# Generated by Django 4.2.3 on 2023-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
