# Generated by Django 4.2.3 on 2023-09-26 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
