# Generated by Django 4.2.3 on 2023-10-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_refered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
