# Generated by Django 4.2.5 on 2023-09-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_login_otp_user_login_otp_used_user_otp_base32_and_more'),
        ('user', '0007_user_refered'),
    ]

    operations = [
    ]
