# Generated by Django 4.2.3 on 2023-10-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_merge_20230930_0656"),
        ("user", "0008_user_is_suscribed_alter_user_is_active"),
    ]

    operations = []
