# Generated by Django 4.2.3 on 2023-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_merge_20231009_0617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
