# Generated by Django 4.2.3 on 2023-10-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_is_connected_to_authunticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_set_trade',
            field=models.BooleanField(default=False),
        ),
    ]
